//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gss.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppCommonConfig_ZD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppCommonConfig_ZD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gss.Entities.AppCommonConfig_ZD", typeof(AppCommonConfig_ZD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/ArticlesInfo.aspx.
        /// </summary>
        internal static string ArticlesInfo_ImitateConnectType {
            get {
                return ResourceManager.GetString("ArticlesInfo_ImitateConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/ArticlesInfo.aspx.
        /// </summary>
        internal static string ArticlesInfo_StockConnectType {
            get {
                return ResourceManager.GetString("ArticlesInfo_StockConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.0.26:8075/BzjService.svc.
        /// </summary>
        internal static string BzjService_ImitateConnectType {
            get {
                return ResourceManager.GetString("BzjService_ImitateConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.0.26:8075/BzjService.svc.
        /// </summary>
        internal static string BzjService_StockConnectType {
            get {
                return ResourceManager.GetString("BzjService_StockConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/GssManager.svc.
        /// </summary>
        internal static string GssManager_ImitateConnectType {
            get {
                return ResourceManager.GetString("GssManager_ImitateConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/GssManager.svc.
        /// </summary>
        internal static string GssManager_StockConnectType {
            get {
                return ResourceManager.GetString("GssManager_StockConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JgjWebService {
            get {
                return ResourceManager.GetString("JgjWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/NewsInfo.aspx.
        /// </summary>
        internal static string NewsAddOrEdit_ImitateConnectType {
            get {
                return ResourceManager.GetString("NewsAddOrEdit_ImitateConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/NewsInfo.aspx.
        /// </summary>
        internal static string NewsAddOrEdit_StockConnectType {
            get {
                return ResourceManager.GetString("NewsAddOrEdit_StockConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/News.aspx.
        /// </summary>
        internal static string NewsShow_ImitateConnectType {
            get {
                return ResourceManager.GetString("NewsShow_ImitateConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/News.aspx.
        /// </summary>
        internal static string NewsShow_StockConnectType {
            get {
                return ResourceManager.GetString("NewsShow_StockConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://121.40.153.156/ZhongDingWeiYeWeiXinNew/services/createTicket?wsdl.
        /// </summary>
        internal static string OrgTicketService_ImitateConnectType {
            get {
                return ResourceManager.GetString("OrgTicketService_ImitateConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://121.40.153.156/ZhongDingWeiYeWeiXinNew/services/createTicket?wsdl.
        /// </summary>
        internal static string OrgTicketService_StockConnectType {
            get {
                return ResourceManager.GetString("OrgTicketService_StockConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string srvUpdateAddr {
            get {
                return ResourceManager.GetString("srvUpdateAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string srvUptFileVersion {
            get {
                return ResourceManager.GetString("srvUptFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/TradeService.svc.
        /// </summary>
        internal static string TradeService_ImitateConnectType {
            get {
                return ResourceManager.GetString("TradeService_ImitateConnectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://192.168.2.102:8077/TradeService.svc.
        /// </summary>
        internal static string TradeService_StockConnectType {
            get {
                return ResourceManager.GetString("TradeService_StockConnectType", resourceCulture);
            }
        }
    }
}
