//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gss.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppPrivilegeConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppPrivilegeConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gss.Entities.AppPrivilegeConfig", typeof(AppPrivilegeConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户管理.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户管理.
        /// </summary>
        public static string Account_Client {
            get {
                return ResourceManager.GetString("Account_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户账户资料.
        /// </summary>
        public static string Account_Client_AccountInfo {
            get {
                return ResourceManager.GetString("Account_Client_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增客户账户.
        /// </summary>
        public static string Account_Client_AddAccount {
            get {
                return ResourceManager.GetString("Account_Client_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调节.
        /// </summary>
        public static string Account_Client_AdjustMoney {
            get {
                return ResourceManager.GetString("Account_Client_AdjustMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除客户账户.
        /// </summary>
        public static string Account_Client_DelAccount {
            get {
                return ResourceManager.GetString("Account_Client_DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户资金信息.
        /// </summary>
        public static string Account_Client_FundsInfo {
            get {
                return ResourceManager.GetString("Account_Client_FundsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改冻结资金.
        /// </summary>
        public static string Account_Client_FundsInfo_Ok {
            get {
                return ResourceManager.GetString("Account_Client_FundsInfo_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 即时成交.
        /// </summary>
        public static string Account_Client_MarketOrder {
            get {
                return ResourceManager.GetString("Account_Client_MarketOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Account_Client_OrderInfo {
            get {
                return ResourceManager.GetString("Account_Client_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挂单交易.
        /// </summary>
        public static string Account_Client_PendingOrder {
            get {
                return ResourceManager.GetString("Account_Client_PendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员.
        /// </summary>
        public static string Account_Manager {
            get {
                return ResourceManager.GetString("Account_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员资料.
        /// </summary>
        public static string Account_Manager_AccountInfo {
            get {
                return ResourceManager.GetString("Account_Manager_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增管理员.
        /// </summary>
        public static string Account_Manager_AddAccount {
            get {
                return ResourceManager.GetString("Account_Manager_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除管理员.
        /// </summary>
        public static string Account_Manager_DelAccount {
            get {
                return ResourceManager.GetString("Account_Manager_DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色权限.
        /// </summary>
        public static string Account_Manager_Role {
            get {
                return ResourceManager.GetString("Account_Manager_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线客户.
        /// </summary>
        public static string Account_Online {
            get {
                return ResourceManager.GetString("Account_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户资料.
        /// </summary>
        public static string Account_Online_AccountInfo {
            get {
                return ResourceManager.GetString("Account_Online_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除账户.
        /// </summary>
        public static string Account_Online_DelAccount {
            get {
                return ResourceManager.GetString("Account_Online_DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资金信息.
        /// </summary>
        public static string Account_Online_FundsInfo {
            get {
                return ResourceManager.GetString("Account_Online_FundsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Account_Online_OrderInfo {
            get {
                return ResourceManager.GetString("Account_Online_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微会员.
        /// </summary>
        public static string Account_Org {
            get {
                return ResourceManager.GetString("Account_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微会员资料.
        /// </summary>
        public static string Account_Org_AccountInfo {
            get {
                return ResourceManager.GetString("Account_Org_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增微会员.
        /// </summary>
        public static string Account_Org_AddAccount {
            get {
                return ResourceManager.GetString("Account_Org_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除微会员.
        /// </summary>
        public static string Account_Org_DelAccount {
            get {
                return ResourceManager.GetString("Account_Org_DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微会员角色.
        /// </summary>
        public static string Account_Org_Role {
            get {
                return ResourceManager.GetString("Account_Org_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 批量返佣.
        /// </summary>
        public static string Account_Org_SetAllCommissionRatio {
            get {
                return ResourceManager.GetString("Account_Org_SetAllCommissionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改返佣.
        /// </summary>
        public static string Account_Org_SetCommissionRatio {
            get {
                return ResourceManager.GetString("Account_Org_SetCommissionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改默认返佣.
        /// </summary>
        public static string Account_Org_SetDefaultCommissionRatio {
            get {
                return ResourceManager.GetString("Account_Org_SetDefaultCommissionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员账户.
        /// </summary>
        public static string Account_OrgAccount {
            get {
                return ResourceManager.GetString("Account_OrgAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员账户资料.
        /// </summary>
        public static string Account_OrgAccount_AccountInfo {
            get {
                return ResourceManager.GetString("Account_OrgAccount_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增会员账户.
        /// </summary>
        public static string Account_OrgAccount_AddAccount {
            get {
                return ResourceManager.GetString("Account_OrgAccount_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除会员账户.
        /// </summary>
        public static string Account_OrgAccount_DelAccount {
            get {
                return ResourceManager.GetString("Account_OrgAccount_DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员账户角色.
        /// </summary>
        public static string Account_OrgAccount_Role {
            get {
                return ResourceManager.GetString("Account_OrgAccount_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据管理.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体验券.
        /// </summary>
        public static string Data_Effective {
            get {
                return ResourceManager.GetString("Data_Effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史数据.
        /// </summary>
        public static string Data_HistoryData {
            get {
                return ResourceManager.GetString("Data_HistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 商品管理.
        /// </summary>
        public static string Data_ProductInfo {
            get {
                return ResourceManager.GetString("Data_ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手工报价.
        /// </summary>
        public static string Data_ProductInfo_ManualPrice {
            get {
                return ResourceManager.GetString("Data_ProductInfo_ManualPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 汇率/水.
        /// </summary>
        public static string Data_RateWaterInfo {
            get {
                return ResourceManager.GetString("Data_RateWaterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 历史数据.
        /// </summary>
        public static string Data_String2 {
            get {
                return ResourceManager.GetString("Data_String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统设置.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新闻公告.
        /// </summary>
        public static string System_1 {
            get {
                return ResourceManager.GetString("System_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告发布.
        /// </summary>
        public static string System_2 {
            get {
                return ResourceManager.GetString("System_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 理财师说.
        /// </summary>
        public static string System_ArticlesInfo {
            get {
                return ResourceManager.GetString("System_ArticlesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户分组管理.
        /// </summary>
        public static string System_Group {
            get {
                return ResourceManager.GetString("System_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节假日管理.
        /// </summary>
        public static string System_Holiday {
            get {
                return ResourceManager.GetString("System_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP地址过滤.
        /// </summary>
        public static string System_IPAddrFilter {
            get {
                return ResourceManager.GetString("System_IPAddrFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志记录.
        /// </summary>
        public static string System_LogInfo {
            get {
                return ResourceManager.GetString("System_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC地址过滤.
        /// </summary>
        public static string System_MACFilter {
            get {
                return ResourceManager.GetString("System_MACFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限管理.
        /// </summary>
        public static string System_PrivilegeManager {
            get {
                return ResourceManager.GetString("System_PrivilegeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色管理.
        /// </summary>
        public static string System_RoleManager {
            get {
                return ResourceManager.GetString("System_RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出入金提示.
        /// </summary>
        public static string System_TradeMoneyInfo {
            get {
                return ResourceManager.GetString("System_TradeMoneyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易日管理.
        /// </summary>
        public static string System_TradingDay {
            get {
                return ResourceManager.GetString("System_TradingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易设置管理.
        /// </summary>
        public static string System_TradingSetting {
            get {
                return ResourceManager.GetString("System_TradingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提货受理.
        /// </summary>
        public static string TakeGoods {
            get {
                return ResourceManager.GetString("TakeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 受理明细.
        /// </summary>
        public static string TakeGoods_AcceptDetail {
            get {
                return ResourceManager.GetString("TakeGoods_AcceptDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定账号.
        /// </summary>
        public static string TakeGoods_BindingAccount {
            get {
                return ResourceManager.GetString("TakeGoods_BindingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提货.
        /// </summary>
        public static string TakeGoods_TakeGoods {
            get {
                return ResourceManager.GetString("TakeGoods_TakeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交易管理.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 买跌单.
        /// </summary>
        public static string Trade_BackGoods {
            get {
                return ResourceManager.GetString("Trade_BackGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平仓历史.
        /// </summary>
        public static string Trade_ChargebackRecode {
            get {
                return ResourceManager.GetString("Trade_ChargebackRecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Trade_ChargebackRecode_OrderInfo {
            get {
                return ResourceManager.GetString("Trade_ChargebackRecode_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出金处理.
        /// </summary>
        public static string Trade_ChuJin {
            get {
                return ResourceManager.GetString("Trade_ChuJin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出入金详情.
        /// </summary>
        public static string Trade_ChuJin_Details {
            get {
                return ResourceManager.GetString("Trade_ChuJin_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Trade_ChuJin_OrderInfo {
            get {
                return ResourceManager.GetString("Trade_ChuJin_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交割单.
        /// </summary>
        public static string Trade_DeliveryGoods {
            get {
                return ResourceManager.GetString("Trade_DeliveryGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出报表.
        /// </summary>
        public static string Trade_ExportStatements {
            get {
                return ResourceManager.GetString("Trade_ExportStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平仓报表.
        /// </summary>
        public static string Trade_ExportStatements_AdjustReport {
            get {
                return ResourceManager.GetString("Trade_ExportStatements_AdjustReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资金报表.
        /// </summary>
        public static string Trade_ExportStatements_FundReport {
            get {
                return ResourceManager.GetString("Trade_ExportStatements_FundReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单报表.
        /// </summary>
        public static string Trade_ExportStatements_MarketOrderReport {
            get {
                return ResourceManager.GetString("Trade_ExportStatements_MarketOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 挂单报表.
        /// </summary>
        public static string Trade_ExportStatements_PendingOrderReport {
            get {
                return ResourceManager.GetString("Trade_ExportStatements_PendingOrderReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资金明细.
        /// </summary>
        public static string Trade_FundReport {
            get {
                return ResourceManager.GetString("Trade_FundReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Trade_FundReport_OrderInfo {
            get {
                return ResourceManager.GetString("Trade_FundReport_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 对冲交易.
        /// </summary>
        public static string Trade_HedgeTrade {
            get {
                return ResourceManager.GetString("Trade_HedgeTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金生金单.
        /// </summary>
        public static string Trade_JgjGoods {
            get {
                return ResourceManager.GetString("Trade_JgjGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会员报表.
        /// </summary>
        public static string Trade_JujianManager {
            get {
                return ResourceManager.GetString("Trade_JujianManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在手订单.
        /// </summary>
        public static string Trade_MarketOrder {
            get {
                return ResourceManager.GetString("Trade_MarketOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平仓.
        /// </summary>
        public static string Trade_MarketOrder_Chargeback {
            get {
                return ResourceManager.GetString("Trade_MarketOrder_Chargeback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Trade_MarketOrder_OrderInfo {
            get {
                return ResourceManager.GetString("Trade_MarketOrder_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 委托订单.
        /// </summary>
        public static string Trade_PendingOrder {
            get {
                return ResourceManager.GetString("Trade_PendingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        public static string Trade_PendingOrder_Cancel {
            get {
                return ResourceManager.GetString("Trade_PendingOrder_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Trade_PendingOrder_OrderInfo {
            get {
                return ResourceManager.GetString("Trade_PendingOrder_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提货单.
        /// </summary>
        public static string Trade_TakeGoods {
            get {
                return ResourceManager.GetString("Trade_TakeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解约处理.
        /// </summary>
        public static string Trade_Termination {
            get {
                return ResourceManager.GetString("Trade_Termination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 审核解约.
        /// </summary>
        public static string Trade_Termination_Approved {
            get {
                return ResourceManager.GetString("Trade_Termination_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 订单信息.
        /// </summary>
        public static string Trade_Termination_OrderInfo {
            get {
                return ResourceManager.GetString("Trade_Termination_OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒绝解约.
        /// </summary>
        public static string Trade_Termination_Reject {
            get {
                return ResourceManager.GetString("Trade_Termination_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入库订单.
        /// </summary>
        public static string Trade_WarehousingOrder {
            get {
                return ResourceManager.GetString("Trade_WarehousingOrder", resourceCulture);
            }
        }
    }
}
