//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gss.Entities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gss.Entities.ErrorText", typeof(ErrorText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取管理员信息失败，请稍后再试！.
        /// </summary>
        public static string GetAdminList {
            get {
                return ResourceManager.GetString("GetAdminList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取委托订单历史记录失败，请稍后再试！.
        /// </summary>
        public static string GetChargebackRecorder {
            get {
                return ResourceManager.GetString("GetChargebackRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取客户资金信息失败，请稍后再试!.
        /// </summary>
        public static string GetClientFundsInfo {
            get {
                return ResourceManager.GetString("GetClientFundsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取客户数据失败，请稍后再试!.
        /// </summary>
        public static string GetClientInfoError {
            get {
                return ResourceManager.GetString("GetClientInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取会员账户信息失败，请稍后再试！.
        /// </summary>
        public static string GetDealerList {
            get {
                return ResourceManager.GetString("GetDealerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取报表地址信息失败，请稍后再试！.
        /// </summary>
        public static string GetExportStatementsWebAddr {
            get {
                return ResourceManager.GetString("GetExportStatementsWebAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取对冲交易信息失败，请稍后再试！.
        /// </summary>
        public static string GetHedgingTradeList {
            get {
                return ResourceManager.GetString("GetHedgingTradeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取历史数据信息失败，请稍后再试！.
        /// </summary>
        public static string GetHistoryData {
            get {
                return ResourceManager.GetString("GetHistoryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取节假日信息失败，请稍后再试！.
        /// </summary>
        public static string GetHolidayInfo {
            get {
                return ResourceManager.GetString("GetHolidayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取IP地址过滤信息列表失败，请稍后再试！.
        /// </summary>
        public static string GetIPAddrFilteringInfoList {
            get {
                return ResourceManager.GetString("GetIPAddrFilteringInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取日志信息失败，请稍后再试！.
        /// </summary>
        public static string GetLogInfo {
            get {
                return ResourceManager.GetString("GetLogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取MAC地址过滤信息列表失败，请稍后再试！.
        /// </summary>
        public static string GetMACFilterInfoList {
            get {
                return ResourceManager.GetString("GetMACFilterInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取在手订单信息失败，请稍后再试！.
        /// </summary>
        public static string GetMarketOrderList {
            get {
                return ResourceManager.GetString("GetMarketOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取在线客户信息失败，请稍后再试！.
        /// </summary>
        public static string GetOnlineClientList {
            get {
                return ResourceManager.GetString("GetOnlineClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取委托订单信息失败，请稍后再试！.
        /// </summary>
        public static string GetPendingOrderList {
            get {
                return ResourceManager.GetString("GetPendingOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取商品信息列表失败，请稍后再试！.
        /// </summary>
        public static string GetProductInfoList {
            get {
                return ResourceManager.GetString("GetProductInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取汇率和水信息列表失败，请稍后再试！.
        /// </summary>
        public static string GetRateWaterInfoList {
            get {
                return ResourceManager.GetString("GetRateWaterInfoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取新闻公告信息失败，请稍后再试！.
        /// </summary>
        public static string GetTradeNewsInfo {
            get {
                return ResourceManager.GetString("GetTradeNewsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取交易设置记录失败，请稍后再试！.
        /// </summary>
        public static string GetTradeSetInfo {
            get {
                return ResourceManager.GetString("GetTradeSetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取交易日信息失败，请稍后再试！.
        /// </summary>
        public static string GetTradingDayInfo {
            get {
                return ResourceManager.GetString("GetTradingDayInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取入库单历史记录列表失败，请稍后再试！.
        /// </summary>
        public static string GetWarehousingRecorder {
            get {
                return ResourceManager.GetString("GetWarehousingRecorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败，请稍后再试!.
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询出错，请稍后再试!.
        /// </summary>
        public static string QueryError {
            get {
                return ResourceManager.GetString("QueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获取用户角色失败，请稍后再试！.
        /// </summary>
        public static string ReadUserRole {
            get {
                return ResourceManager.GetString("ReadUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络连接失败，请检查您的网络连接状态后重试！.
        /// </summary>
        public static string ServiceError {
            get {
                return ResourceManager.GetString("ServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器连接超时，请稍后重试！.
        /// </summary>
        public static string TimeoutException {
            get {
                return ResourceManager.GetString("TimeoutException", resourceCulture);
            }
        }
    }
}
