//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gss.BzjService.JgjServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JgjServiceReference.JgjServiceSoap")]
    public interface JgjServiceSoap {
        
        // CODEGEN: Generating message contract since element name accountLoginId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserExist", ReplyAction="*")]
        Gss.BzjService.JgjServiceReference.IsUserExistResponse IsUserExist(Gss.BzjService.JgjServiceReference.IsUserExistRequest request);
        
        // CODEGEN: Generating message contract since element name accountLoginId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserRegister", ReplyAction="*")]
        Gss.BzjService.JgjServiceReference.UserRegisterResponse UserRegister(Gss.BzjService.JgjServiceReference.UserRegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserExistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserExist", Namespace="http://tempuri.org/", Order=0)]
        public Gss.BzjService.JgjServiceReference.IsUserExistRequestBody Body;
        
        public IsUserExistRequest() {
        }
        
        public IsUserExistRequest(Gss.BzjService.JgjServiceReference.IsUserExistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsUserExistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int certificate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountLoginId;
        
        public IsUserExistRequestBody() {
        }
        
        public IsUserExistRequestBody(int certificate, string accountLoginId) {
            this.certificate = certificate;
            this.accountLoginId = accountLoginId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserExistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserExistResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gss.BzjService.JgjServiceReference.IsUserExistResponseBody Body;
        
        public IsUserExistResponse() {
        }
        
        public IsUserExistResponse(Gss.BzjService.JgjServiceReference.IsUserExistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsUserExistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IsUserExistResult;
        
        public IsUserExistResponseBody() {
        }
        
        public IsUserExistResponseBody(int IsUserExistResult) {
            this.IsUserExistResult = IsUserExistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserRegister", Namespace="http://tempuri.org/", Order=0)]
        public Gss.BzjService.JgjServiceReference.UserRegisterRequestBody Body;
        
        public UserRegisterRequest() {
        }
        
        public UserRegisterRequest(Gss.BzjService.JgjServiceReference.UserRegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserRegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int certificate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accountLoginId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string agency;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tel;
        
        public UserRegisterRequestBody() {
        }
        
        public UserRegisterRequestBody(int certificate, string accountLoginId, string pwd, string agency, int category, string username, string tel) {
            this.certificate = certificate;
            this.accountLoginId = accountLoginId;
            this.pwd = pwd;
            this.agency = agency;
            this.category = category;
            this.username = username;
            this.tel = tel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserRegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gss.BzjService.JgjServiceReference.UserRegisterResponseBody Body;
        
        public UserRegisterResponse() {
        }
        
        public UserRegisterResponse(Gss.BzjService.JgjServiceReference.UserRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserRegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserRegisterResult;
        
        public UserRegisterResponseBody() {
        }
        
        public UserRegisterResponseBody(string UserRegisterResult) {
            this.UserRegisterResult = UserRegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JgjServiceSoapChannel : Gss.BzjService.JgjServiceReference.JgjServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JgjServiceSoapClient : System.ServiceModel.ClientBase<Gss.BzjService.JgjServiceReference.JgjServiceSoap>, Gss.BzjService.JgjServiceReference.JgjServiceSoap {
        
        public JgjServiceSoapClient() {
        }
        
        public JgjServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JgjServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JgjServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JgjServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gss.BzjService.JgjServiceReference.IsUserExistResponse Gss.BzjService.JgjServiceReference.JgjServiceSoap.IsUserExist(Gss.BzjService.JgjServiceReference.IsUserExistRequest request) {
            return base.Channel.IsUserExist(request);
        }
        
        public int IsUserExist(int certificate, string accountLoginId) {
            Gss.BzjService.JgjServiceReference.IsUserExistRequest inValue = new Gss.BzjService.JgjServiceReference.IsUserExistRequest();
            inValue.Body = new Gss.BzjService.JgjServiceReference.IsUserExistRequestBody();
            inValue.Body.certificate = certificate;
            inValue.Body.accountLoginId = accountLoginId;
            Gss.BzjService.JgjServiceReference.IsUserExistResponse retVal = ((Gss.BzjService.JgjServiceReference.JgjServiceSoap)(this)).IsUserExist(inValue);
            return retVal.Body.IsUserExistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gss.BzjService.JgjServiceReference.UserRegisterResponse Gss.BzjService.JgjServiceReference.JgjServiceSoap.UserRegister(Gss.BzjService.JgjServiceReference.UserRegisterRequest request) {
            return base.Channel.UserRegister(request);
        }
        
        public string UserRegister(int certificate, string accountLoginId, string pwd, string agency, int category, string username, string tel) {
            Gss.BzjService.JgjServiceReference.UserRegisterRequest inValue = new Gss.BzjService.JgjServiceReference.UserRegisterRequest();
            inValue.Body = new Gss.BzjService.JgjServiceReference.UserRegisterRequestBody();
            inValue.Body.certificate = certificate;
            inValue.Body.accountLoginId = accountLoginId;
            inValue.Body.pwd = pwd;
            inValue.Body.agency = agency;
            inValue.Body.category = category;
            inValue.Body.username = username;
            inValue.Body.tel = tel;
            Gss.BzjService.JgjServiceReference.UserRegisterResponse retVal = ((Gss.BzjService.JgjServiceReference.JgjServiceSoap)(this)).UserRegister(inValue);
            return retVal.Body.UserRegisterResult;
        }
    }
}
