//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gss.BusinessService.OrgTicketService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.0.151:8080/JiuXingWeiXin/services/createTicket", ConfigurationName="OrgTicketService.OrgTicket")]
    public interface OrgTicket {
        
        // CODEGEN: 消息 createRequest 的包装命名空间(http://ws.mossle.com)以后生成的消息协定与默认值(http://192.168.0.151:8080/JiuXingWeiXin/services/createTicket)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Gss.BusinessService.OrgTicketService.createResponse create(Gss.BusinessService.OrgTicketService.createRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://ws.mossle.com", IsWrapped=true)]
    public partial class createRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string inXml;
        
        public createRequest() {
        }
        
        public createRequest(string inXml) {
            this.inXml = inXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://192.168.0.151:8080/JiuXingWeiXin/services/createTicket", IsWrapped=true)]
    public partial class createResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public object createReturn;
        
        public createResponse() {
        }
        
        public createResponse(object createReturn) {
            this.createReturn = createReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrgTicketChannel : Gss.BusinessService.OrgTicketService.OrgTicket, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrgTicketClient : System.ServiceModel.ClientBase<Gss.BusinessService.OrgTicketService.OrgTicket>, Gss.BusinessService.OrgTicketService.OrgTicket {
        
        public OrgTicketClient() {
        }
        
        public OrgTicketClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrgTicketClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrgTicketClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrgTicketClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gss.BusinessService.OrgTicketService.createResponse Gss.BusinessService.OrgTicketService.OrgTicket.create(Gss.BusinessService.OrgTicketService.createRequest request) {
            return base.Channel.create(request);
        }
        
        public object create(string inXml) {
            Gss.BusinessService.OrgTicketService.createRequest inValue = new Gss.BusinessService.OrgTicketService.createRequest();
            inValue.inXml = inXml;
            Gss.BusinessService.OrgTicketService.createResponse retVal = ((Gss.BusinessService.OrgTicketService.OrgTicket)(this)).create(inValue);
            return retVal.createReturn;
        }
    }
}
