//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gss.BzjService.BZJServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gss.BzjService.BZJServiceReference.OrderTypeTotal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gss.BzjService.BZJServiceReference.UserBindEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gss.BzjService.BZJServiceReference.OrderEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gss.BzjService.BZJServiceReference.DeliverEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gss.BzjService.BZJServiceReference.VerifyCodeEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gss.BzjService.BZJServiceReference.StockEntity))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable DataSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable DataSource {
            get {
                return this.DataSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSourceField, value) != true)) {
                    this.DataSourceField = value;
                    this.RaisePropertyChanged("DataSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderTypeTotal", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class OrderTypeTotal : Gss.BzjService.BZJServiceReference.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AskOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AskSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BidOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BidSuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AskOrder {
            get {
                return this.AskOrderField;
            }
            set {
                if ((this.AskOrderField.Equals(value) != true)) {
                    this.AskOrderField = value;
                    this.RaisePropertyChanged("AskOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AskSuccess {
            get {
                return this.AskSuccessField;
            }
            set {
                if ((this.AskSuccessField.Equals(value) != true)) {
                    this.AskSuccessField = value;
                    this.RaisePropertyChanged("AskSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BidOrder {
            get {
                return this.BidOrderField;
            }
            set {
                if ((this.BidOrderField.Equals(value) != true)) {
                    this.BidOrderField = value;
                    this.RaisePropertyChanged("BidOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BidSuccess {
            get {
                return this.BidSuccessField;
            }
            set {
                if ((this.BidSuccessField.Equals(value) != true)) {
                    this.BidSuccessField = value;
                    this.RaisePropertyChanged("BidSuccess");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBindEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class UserBindEntity : Gss.BzjService.BZJServiceReference.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsEnableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserBindIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateField, value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsEnable {
            get {
                return this.IsEnableField;
            }
            set {
                if ((this.IsEnableField.Equals(value) != true)) {
                    this.IsEnableField = value;
                    this.RaisePropertyChanged("IsEnable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JUserId {
            get {
                return this.JUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.JUserIdField, value) != true)) {
                    this.JUserIdField = value;
                    this.RaisePropertyChanged("JUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserBindId {
            get {
                return this.UserBindIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserBindIdField, value) != true)) {
                    this.UserBindIdField = value;
                    this.RaisePropertyChanged("UserBindId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class OrderEntity : Gss.BzjService.BZJServiceReference.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Ag_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Au_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarryWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClerkIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CeritificateEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Pd_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Pt_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tradeAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ag {
            get {
                return this.AgField;
            }
            set {
                if ((this.AgField.Equals(value) != true)) {
                    this.AgField = value;
                    this.RaisePropertyChanged("Ag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgAmount {
            get {
                return this.AgAmountField;
            }
            set {
                if ((this.AgAmountField.Equals(value) != true)) {
                    this.AgAmountField = value;
                    this.RaisePropertyChanged("AgAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgCost {
            get {
                return this.AgCostField;
            }
            set {
                if ((this.AgCostField.Equals(value) != true)) {
                    this.AgCostField = value;
                    this.RaisePropertyChanged("AgCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgP {
            get {
                return this.AgPField;
            }
            set {
                if ((this.AgPField.Equals(value) != true)) {
                    this.AgPField = value;
                    this.RaisePropertyChanged("AgP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgQuantity {
            get {
                return this.AgQuantityField;
            }
            set {
                if ((this.AgQuantityField.Equals(value) != true)) {
                    this.AgQuantityField = value;
                    this.RaisePropertyChanged("AgQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgT {
            get {
                return this.AgTField;
            }
            set {
                if ((this.AgTField.Equals(value) != true)) {
                    this.AgTField = value;
                    this.RaisePropertyChanged("AgT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ag_b {
            get {
                return this.Ag_bField;
            }
            set {
                if ((this.Ag_bField.Equals(value) != true)) {
                    this.Ag_bField = value;
                    this.RaisePropertyChanged("Ag_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID {
            get {
                return this.AgentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentIDField, value) != true)) {
                    this.AgentIDField = value;
                    this.RaisePropertyChanged("AgentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentName {
            get {
                return this.AgentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNameField, value) != true)) {
                    this.AgentNameField = value;
                    this.RaisePropertyChanged("AgentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentUserID {
            get {
                return this.AgentUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentUserIDField, value) != true)) {
                    this.AgentUserIDField = value;
                    this.RaisePropertyChanged("AgentUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Au {
            get {
                return this.AuField;
            }
            set {
                if ((this.AuField.Equals(value) != true)) {
                    this.AuField = value;
                    this.RaisePropertyChanged("Au");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuAmount {
            get {
                return this.AuAmountField;
            }
            set {
                if ((this.AuAmountField.Equals(value) != true)) {
                    this.AuAmountField = value;
                    this.RaisePropertyChanged("AuAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuCost {
            get {
                return this.AuCostField;
            }
            set {
                if ((this.AuCostField.Equals(value) != true)) {
                    this.AuCostField = value;
                    this.RaisePropertyChanged("AuCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuP {
            get {
                return this.AuPField;
            }
            set {
                if ((this.AuPField.Equals(value) != true)) {
                    this.AuPField = value;
                    this.RaisePropertyChanged("AuP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuQuantity {
            get {
                return this.AuQuantityField;
            }
            set {
                if ((this.AuQuantityField.Equals(value) != true)) {
                    this.AuQuantityField = value;
                    this.RaisePropertyChanged("AuQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuT {
            get {
                return this.AuTField;
            }
            set {
                if ((this.AuTField.Equals(value) != true)) {
                    this.AuTField = value;
                    this.RaisePropertyChanged("AuT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Au_b {
            get {
                return this.Au_bField;
            }
            set {
                if ((this.Au_bField.Equals(value) != true)) {
                    this.Au_bField = value;
                    this.RaisePropertyChanged("Au_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNum {
            get {
                return this.CardNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumField, value) != true)) {
                    this.CardNumField = value;
                    this.RaisePropertyChanged("CardNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((this.CardTypeField.Equals(value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarryWay {
            get {
                return this.CarryWayField;
            }
            set {
                if ((this.CarryWayField.Equals(value) != true)) {
                    this.CarryWayField = value;
                    this.RaisePropertyChanged("CarryWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClerkID {
            get {
                return this.ClerkIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClerkIDField, value) != true)) {
                    this.ClerkIDField = value;
                    this.RaisePropertyChanged("ClerkID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateField, value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNo {
            get {
                return this.IDNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNoField, value) != true)) {
                    this.IDNoField = value;
                    this.RaisePropertyChanged("IDNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public int CeritificateEnum {
            get {
                return this.CeritificateEnumField;
            }
            set {
                if ((this.CeritificateEnumField.Equals(value) != true)) {
                    this.CeritificateEnumField = value;
                    this.RaisePropertyChanged("CeritificateEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string JUserId {
            get {
                return this.JUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.JUserIdField, value) != true)) {
                    this.JUserIdField = value;
                    this.RaisePropertyChanged("JUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string OperationDate {
            get {
                return this.OperationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationDateField, value) != true)) {
                    this.OperationDateField = value;
                    this.RaisePropertyChanged("OperationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string OrderCode {
            get {
                return this.OrderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderCodeField, value) != true)) {
                    this.OrderCodeField = value;
                    this.RaisePropertyChanged("OrderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=32)]
        public int OrderType {
            get {
                return this.OrderTypeField;
            }
            set {
                if ((this.OrderTypeField.Equals(value) != true)) {
                    this.OrderTypeField = value;
                    this.RaisePropertyChanged("OrderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=33)]
        public decimal Pd {
            get {
                return this.PdField;
            }
            set {
                if ((this.PdField.Equals(value) != true)) {
                    this.PdField = value;
                    this.RaisePropertyChanged("Pd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=34)]
        public decimal PdAmount {
            get {
                return this.PdAmountField;
            }
            set {
                if ((this.PdAmountField.Equals(value) != true)) {
                    this.PdAmountField = value;
                    this.RaisePropertyChanged("PdAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=35)]
        public decimal PdCost {
            get {
                return this.PdCostField;
            }
            set {
                if ((this.PdCostField.Equals(value) != true)) {
                    this.PdCostField = value;
                    this.RaisePropertyChanged("PdCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=36)]
        public decimal PdP {
            get {
                return this.PdPField;
            }
            set {
                if ((this.PdPField.Equals(value) != true)) {
                    this.PdPField = value;
                    this.RaisePropertyChanged("PdP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=37)]
        public decimal PdQuantity {
            get {
                return this.PdQuantityField;
            }
            set {
                if ((this.PdQuantityField.Equals(value) != true)) {
                    this.PdQuantityField = value;
                    this.RaisePropertyChanged("PdQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=38)]
        public decimal PdT {
            get {
                return this.PdTField;
            }
            set {
                if ((this.PdTField.Equals(value) != true)) {
                    this.PdTField = value;
                    this.RaisePropertyChanged("PdT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=39)]
        public decimal Pd_b {
            get {
                return this.Pd_bField;
            }
            set {
                if ((this.Pd_bField.Equals(value) != true)) {
                    this.Pd_bField = value;
                    this.RaisePropertyChanged("Pd_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=40)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=41)]
        public string PhoneNum {
            get {
                return this.PhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumField, value) != true)) {
                    this.PhoneNumField = value;
                    this.RaisePropertyChanged("PhoneNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=42)]
        public decimal Pt {
            get {
                return this.PtField;
            }
            set {
                if ((this.PtField.Equals(value) != true)) {
                    this.PtField = value;
                    this.RaisePropertyChanged("Pt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=43)]
        public decimal PtAmount {
            get {
                return this.PtAmountField;
            }
            set {
                if ((this.PtAmountField.Equals(value) != true)) {
                    this.PtAmountField = value;
                    this.RaisePropertyChanged("PtAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=44)]
        public decimal PtCost {
            get {
                return this.PtCostField;
            }
            set {
                if ((this.PtCostField.Equals(value) != true)) {
                    this.PtCostField = value;
                    this.RaisePropertyChanged("PtCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=45)]
        public decimal PtP {
            get {
                return this.PtPField;
            }
            set {
                if ((this.PtPField.Equals(value) != true)) {
                    this.PtPField = value;
                    this.RaisePropertyChanged("PtP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=46)]
        public decimal PtQuantity {
            get {
                return this.PtQuantityField;
            }
            set {
                if ((this.PtQuantityField.Equals(value) != true)) {
                    this.PtQuantityField = value;
                    this.RaisePropertyChanged("PtQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=47)]
        public decimal PtT {
            get {
                return this.PtTField;
            }
            set {
                if ((this.PtTField.Equals(value) != true)) {
                    this.PtTField = value;
                    this.RaisePropertyChanged("PtT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=48)]
        public decimal Pt_b {
            get {
                return this.Pt_bField;
            }
            set {
                if ((this.Pt_bField.Equals(value) != true)) {
                    this.Pt_bField = value;
                    this.RaisePropertyChanged("Pt_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=49)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=50)]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=51)]
        public int TmpId {
            get {
                return this.TmpIdField;
            }
            set {
                if ((this.TmpIdField.Equals(value) != true)) {
                    this.TmpIdField = value;
                    this.RaisePropertyChanged("TmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=52)]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=53)]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=54)]
        public int Version {
            get {
                return this.VersionField;
            }
            set {
                if ((this.VersionField.Equals(value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=55)]
        public string tradeAccount {
            get {
                return this.tradeAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.tradeAccountField, value) != true)) {
                    this.tradeAccountField = value;
                    this.RaisePropertyChanged("tradeAccount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliverEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class DeliverEntity : Gss.BzjService.BZJServiceReference.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailableTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliverDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliverNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DirectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LockPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableTotal {
            get {
                return this.AvailableTotalField;
            }
            set {
                if ((this.AvailableTotalField.Equals(value) != true)) {
                    this.AvailableTotalField = value;
                    this.RaisePropertyChanged("AvailableTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateDateField, value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliverDate {
            get {
                return this.DeliverDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverDateField, value) != true)) {
                    this.DeliverDateField = value;
                    this.RaisePropertyChanged("DeliverDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliverId {
            get {
                return this.DeliverIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverIdField, value) != true)) {
                    this.DeliverIdField = value;
                    this.RaisePropertyChanged("DeliverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliverNo {
            get {
                return this.DeliverNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliverNoField, value) != true)) {
                    this.DeliverNoField = value;
                    this.RaisePropertyChanged("DeliverNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Direction {
            get {
                return this.DirectionField;
            }
            set {
                if ((this.DirectionField.Equals(value) != true)) {
                    this.DirectionField = value;
                    this.RaisePropertyChanged("Direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EndDateField, value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromFlag {
            get {
                return this.FromFlagField;
            }
            set {
                if ((this.FromFlagField.Equals(value) != true)) {
                    this.FromFlagField = value;
                    this.RaisePropertyChanged("FromFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Goods {
            get {
                return this.GoodsField;
            }
            set {
                if ((this.GoodsField.Equals(value) != true)) {
                    this.GoodsField = value;
                    this.RaisePropertyChanged("Goods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LockPrice {
            get {
                return this.LockPriceField;
            }
            set {
                if ((this.LockPriceField.Equals(value) != true)) {
                    this.LockPriceField = value;
                    this.RaisePropertyChanged("LockPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationUserID {
            get {
                return this.OperationUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationUserIDField, value) != true)) {
                    this.OperationUserIDField = value;
                    this.RaisePropertyChanged("OperationUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyCodeEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class VerifyCodeEntity : Gss.BzjService.BZJServiceReference.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VierfyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VierfyCode {
            get {
                return this.VierfyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VierfyCodeField, value) != true)) {
                    this.VierfyCodeField = value;
                    this.RaisePropertyChanged("VierfyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class StockEntity : Gss.BzjService.BZJServiceReference.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AgTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Ag_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AuTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Au_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PdTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Pd_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PtTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Pt_bField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ag {
            get {
                return this.AgField;
            }
            set {
                if ((this.AgField.Equals(value) != true)) {
                    this.AgField = value;
                    this.RaisePropertyChanged("Ag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgAmount {
            get {
                return this.AgAmountField;
            }
            set {
                if ((this.AgAmountField.Equals(value) != true)) {
                    this.AgAmountField = value;
                    this.RaisePropertyChanged("AgAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgPrice {
            get {
                return this.AgPriceField;
            }
            set {
                if ((this.AgPriceField.Equals(value) != true)) {
                    this.AgPriceField = value;
                    this.RaisePropertyChanged("AgPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgTotal {
            get {
                return this.AgTotalField;
            }
            set {
                if ((this.AgTotalField.Equals(value) != true)) {
                    this.AgTotalField = value;
                    this.RaisePropertyChanged("AgTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Ag_b {
            get {
                return this.Ag_bField;
            }
            set {
                if ((this.Ag_bField.Equals(value) != true)) {
                    this.Ag_bField = value;
                    this.RaisePropertyChanged("Ag_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Au {
            get {
                return this.AuField;
            }
            set {
                if ((this.AuField.Equals(value) != true)) {
                    this.AuField = value;
                    this.RaisePropertyChanged("Au");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuAmount {
            get {
                return this.AuAmountField;
            }
            set {
                if ((this.AuAmountField.Equals(value) != true)) {
                    this.AuAmountField = value;
                    this.RaisePropertyChanged("AuAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuPrice {
            get {
                return this.AuPriceField;
            }
            set {
                if ((this.AuPriceField.Equals(value) != true)) {
                    this.AuPriceField = value;
                    this.RaisePropertyChanged("AuPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AuTotal {
            get {
                return this.AuTotalField;
            }
            set {
                if ((this.AuTotalField.Equals(value) != true)) {
                    this.AuTotalField = value;
                    this.RaisePropertyChanged("AuTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Au_b {
            get {
                return this.Au_bField;
            }
            set {
                if ((this.Au_bField.Equals(value) != true)) {
                    this.Au_bField = value;
                    this.RaisePropertyChanged("Au_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pd {
            get {
                return this.PdField;
            }
            set {
                if ((this.PdField.Equals(value) != true)) {
                    this.PdField = value;
                    this.RaisePropertyChanged("Pd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PdAmount {
            get {
                return this.PdAmountField;
            }
            set {
                if ((this.PdAmountField.Equals(value) != true)) {
                    this.PdAmountField = value;
                    this.RaisePropertyChanged("PdAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PdPrice {
            get {
                return this.PdPriceField;
            }
            set {
                if ((this.PdPriceField.Equals(value) != true)) {
                    this.PdPriceField = value;
                    this.RaisePropertyChanged("PdPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PdTotal {
            get {
                return this.PdTotalField;
            }
            set {
                if ((this.PdTotalField.Equals(value) != true)) {
                    this.PdTotalField = value;
                    this.RaisePropertyChanged("PdTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pd_b {
            get {
                return this.Pd_bField;
            }
            set {
                if ((this.Pd_bField.Equals(value) != true)) {
                    this.Pd_bField = value;
                    this.RaisePropertyChanged("Pd_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pt {
            get {
                return this.PtField;
            }
            set {
                if ((this.PtField.Equals(value) != true)) {
                    this.PtField = value;
                    this.RaisePropertyChanged("Pt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PtAmount {
            get {
                return this.PtAmountField;
            }
            set {
                if ((this.PtAmountField.Equals(value) != true)) {
                    this.PtAmountField = value;
                    this.RaisePropertyChanged("PtAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PtPrice {
            get {
                return this.PtPriceField;
            }
            set {
                if ((this.PtPriceField.Equals(value) != true)) {
                    this.PtPriceField = value;
                    this.RaisePropertyChanged("PtPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PtTotal {
            get {
                return this.PtTotalField;
            }
            set {
                if ((this.PtTotalField.Equals(value) != true)) {
                    this.PtTotalField = value;
                    this.RaisePropertyChanged("PtTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pt_b {
            get {
                return this.Pt_bField;
            }
            set {
                if ((this.Pt_bField.Equals(value) != true)) {
                    this.Pt_bField = value;
                    this.RaisePropertyChanged("Pt_b");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockID {
            get {
                return this.StockIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StockIDField, value) != true)) {
                    this.StockIDField = value;
                    this.RaisePropertyChanged("StockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultDesc", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class ResultDesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderAttachEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class OrderAttachEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CeritificateEnumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderAttachIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNo {
            get {
                return this.IDNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNoField, value) != true)) {
                    this.IDNoField = value;
                    this.RaisePropertyChanged("IDNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CeritificateEnum {
            get {
                return this.CeritificateEnumField;
            }
            set {
                if ((this.CeritificateEnumField.Equals(value) != true)) {
                    this.CeritificateEnumField = value;
                    this.RaisePropertyChanged("CeritificateEnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string OrderAttachId {
            get {
                return this.OrderAttachIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderAttachIdField, value) != true)) {
                    this.OrderAttachIdField = value;
                    this.RaisePropertyChanged("OrderAttachId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderOperationEntity", Namespace="http://schemas.datacontract.org/2004/07/WcfInterface.model")]
    [System.SerializableAttribute()]
    public partial class OrderOperationEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationDate {
            get {
                return this.OperationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationDateField, value) != true)) {
                    this.OperationDateField = value;
                    this.RaisePropertyChanged("OperationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationIP {
            get {
                return this.OperationIPField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIPField, value) != true)) {
                    this.OperationIPField = value;
                    this.RaisePropertyChanged("OperationIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIdField, value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.IManagerBzj.com", ConfigurationName="BZJServiceReference.IManagerBzj")]
    public interface IManagerBzj {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetUserStockInfo", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetUserStockInfoResponse")]
        Gss.BzjService.BZJServiceReference.StockEntity GetUserStockInfo(string loginID, string userID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetAdminUserStockInfo", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetAdminUserStockInfoResponse")]
        Gss.BzjService.BZJServiceReference.StockEntity GetAdminUserStockInfo(string loginID, string userID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetAccountStockInfo", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetAccountStockInfoResponse")]
        Gss.BzjService.BZJServiceReference.StockEntity GetAccountStockInfo(string loginID, string account, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetOrderList", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetOrderListResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase GetOrderList(string loginID, string userID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetOrderTotal", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetOrderTotalResponse")]
        Gss.BzjService.BZJServiceReference.OrderTypeTotal GetOrderTotal(string loginID, string userID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateGssUser", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateGssUserResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc CreateGssUser(Gss.BzjService.BZJServiceReference.UserBindEntity entity, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateAdminGssUser", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateAdminGssUserResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc CreateAdminGssUser(Gss.BzjService.BZJServiceReference.UserBindEntity entity, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/UpdateGssUser", ReplyAction="www.IManagerBzj.com/IManagerBzj/UpdateGssUserResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc UpdateGssUser(Gss.BzjService.BZJServiceReference.UserBindEntity entity, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/DelteGssUser", ReplyAction="www.IManagerBzj.com/IManagerBzj/DelteGssUserResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc DelteGssUser(string userBindId, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/ReadGssUser", ReplyAction="www.IManagerBzj.com/IManagerBzj/ReadGssUserResponse")]
        Gss.BzjService.BZJServiceReference.UserBindEntity ReadGssUser(string userBindId, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateOrder", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateOrderResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc CreateOrder(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity entity, Gss.BzjService.BZJServiceReference.OrderAttachEntity attachEntity, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateBackOrder", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateBackOrderResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc CreateBackOrder(Gss.BzjService.BZJServiceReference.OrderEntity entity, Gss.BzjService.BZJServiceReference.OrderOperationEntity operationEntity, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/OrderLog", ReplyAction="www.IManagerBzj.com/IManagerBzj/OrderLogResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase OrderLog(string loginID, string userID, int pageindex, int pagesize, ref int page, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/LoadByOrderHG", ReplyAction="www.IManagerBzj.com/IManagerBzj/LoadByOrderHGResponse")]
        Gss.BzjService.BZJServiceReference.OrderEntity LoadByOrderHG(string orderNo, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateOrderJSJ", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateOrderJSJResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc CreateOrderJSJ(Gss.BzjService.BZJServiceReference.OrderEntity orderEntity, Gss.BzjService.BZJServiceReference.OrderOperationEntity operationEntity, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/UpdateOrder", ReplyAction="www.IManagerBzj.com/IManagerBzj/UpdateOrderResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc UpdateOrder(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, Gss.BzjService.BZJServiceReference.OrderOperationEntity orderOperation, string agentInfoID, string IP, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateDeliverAdmin", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateDeliverAdminResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc CreateDeliverAdmin(Gss.BzjService.BZJServiceReference.DeliverEntity entity, string orderType, string Product, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateVerifyCode", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateVerifyCodeResponse")]
        Gss.BzjService.BZJServiceReference.VerifyCodeEntity CreateVerifyCode(string userID, int OrderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CheckVerifyCode", ReplyAction="www.IManagerBzj.com/IManagerBzj/CheckVerifyCodeResponse")]
        Gss.BzjService.BZJServiceReference.VerifyCodeEntity CheckVerifyCode(string userID, string verifyCode, int OrderType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/AgentBind", ReplyAction="www.IManagerBzj.com/IManagerBzj/AgentBindResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc AgentBind(string account, string agentid, string cardNum, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetAgentOrderList", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetAgentOrderListResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase GetAgentOrderList(string agentID, Gss.BzjService.BZJServiceReference.OrderEntity order, string loginID, int pageindex, int pagesize, ref int page, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetOrderTakeList", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetOrderTakeListResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase GetOrderTakeList(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.OrderEntity> list, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetOrderBackList", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetOrderBackListResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase GetOrderBackList(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.OrderEntity> list, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/UpdateBuyBackOrder", ReplyAction="www.IManagerBzj.com/IManagerBzj/UpdateBuyBackOrderResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase UpdateBuyBackOrder(string loginID, string OrderCode, string agentID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetOrderJsjList", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetOrderJsjListResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase GetOrderJsjList(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.OrderEntity> list, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/CreateStockDeliverAdmin", ReplyAction="www.IManagerBzj.com/IManagerBzj/CreateStockDeliverAdminResponse")]
        Gss.BzjService.BZJServiceReference.ResultDesc CreateStockDeliverAdmin(string operationID, Gss.BzjService.BZJServiceReference.OrderEntity orderEnity, string loginID, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetDeliverList", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetDeliverListResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase GetDeliverList(string loginID, string userID, int deliverType, string startTime, string endTime, int goods, int pageindex, int pagesize, ref int page, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetOrderNOInfo", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetOrderNOInfoResponse")]
        Gss.BzjService.BZJServiceReference.OrderEntity GetOrderNOInfo(string loginID, string orderCode, int roleType);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.IManagerBzj.com/IManagerBzj/GetDeliverOrderList", ReplyAction="www.IManagerBzj.com/IManagerBzj/GetDeliverOrderListResponse")]
        Gss.BzjService.BZJServiceReference.EntityBase GetDeliverOrderList(string loginID, Gss.BzjService.BZJServiceReference.DeliverEntity entity, string name, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.DeliverEntity> list, int roleType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagerBzjChannel : Gss.BzjService.BZJServiceReference.IManagerBzj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagerBzjClient : System.ServiceModel.ClientBase<Gss.BzjService.BZJServiceReference.IManagerBzj>, Gss.BzjService.BZJServiceReference.IManagerBzj {
        
        public ManagerBzjClient() {
        }
        
        public ManagerBzjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagerBzjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerBzjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerBzjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gss.BzjService.BZJServiceReference.StockEntity GetUserStockInfo(string loginID, string userID, int roleType) {
            return base.Channel.GetUserStockInfo(loginID, userID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.StockEntity GetAdminUserStockInfo(string loginID, string userID, int roleType) {
            return base.Channel.GetAdminUserStockInfo(loginID, userID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.StockEntity GetAccountStockInfo(string loginID, string account, int roleType) {
            return base.Channel.GetAccountStockInfo(loginID, account, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase GetOrderList(string loginID, string userID, int roleType) {
            return base.Channel.GetOrderList(loginID, userID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.OrderTypeTotal GetOrderTotal(string loginID, string userID, int roleType) {
            return base.Channel.GetOrderTotal(loginID, userID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc CreateGssUser(Gss.BzjService.BZJServiceReference.UserBindEntity entity, string loginID, int roleType) {
            return base.Channel.CreateGssUser(entity, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc CreateAdminGssUser(Gss.BzjService.BZJServiceReference.UserBindEntity entity, string loginID, int roleType) {
            return base.Channel.CreateAdminGssUser(entity, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc UpdateGssUser(Gss.BzjService.BZJServiceReference.UserBindEntity entity, string loginID, int roleType) {
            return base.Channel.UpdateGssUser(entity, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc DelteGssUser(string userBindId, string loginID, int roleType) {
            return base.Channel.DelteGssUser(userBindId, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.UserBindEntity ReadGssUser(string userBindId, string loginID, int roleType) {
            return base.Channel.ReadGssUser(userBindId, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc CreateOrder(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity entity, Gss.BzjService.BZJServiceReference.OrderAttachEntity attachEntity, int roleType) {
            return base.Channel.CreateOrder(loginID, entity, attachEntity, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc CreateBackOrder(Gss.BzjService.BZJServiceReference.OrderEntity entity, Gss.BzjService.BZJServiceReference.OrderOperationEntity operationEntity, string loginID, int roleType) {
            return base.Channel.CreateBackOrder(entity, operationEntity, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase OrderLog(string loginID, string userID, int pageindex, int pagesize, ref int page, int roleType) {
            return base.Channel.OrderLog(loginID, userID, pageindex, pagesize, ref page, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.OrderEntity LoadByOrderHG(string orderNo, string loginID, int roleType) {
            return base.Channel.LoadByOrderHG(orderNo, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc CreateOrderJSJ(Gss.BzjService.BZJServiceReference.OrderEntity orderEntity, Gss.BzjService.BZJServiceReference.OrderOperationEntity operationEntity, string loginID, int roleType) {
            return base.Channel.CreateOrderJSJ(orderEntity, operationEntity, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc UpdateOrder(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, Gss.BzjService.BZJServiceReference.OrderOperationEntity orderOperation, string agentInfoID, string IP, int roleType) {
            return base.Channel.UpdateOrder(loginID, order, orderOperation, agentInfoID, IP, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc CreateDeliverAdmin(Gss.BzjService.BZJServiceReference.DeliverEntity entity, string orderType, string Product, string loginID, int roleType) {
            return base.Channel.CreateDeliverAdmin(entity, orderType, Product, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.VerifyCodeEntity CreateVerifyCode(string userID, int OrderType) {
            return base.Channel.CreateVerifyCode(userID, OrderType);
        }
        
        public Gss.BzjService.BZJServiceReference.VerifyCodeEntity CheckVerifyCode(string userID, string verifyCode, int OrderType) {
            return base.Channel.CheckVerifyCode(userID, verifyCode, OrderType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc AgentBind(string account, string agentid, string cardNum, string loginID, int roleType) {
            return base.Channel.AgentBind(account, agentid, cardNum, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase GetAgentOrderList(string agentID, Gss.BzjService.BZJServiceReference.OrderEntity order, string loginID, int pageindex, int pagesize, ref int page, int roleType) {
            return base.Channel.GetAgentOrderList(agentID, order, loginID, pageindex, pagesize, ref page, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase GetOrderTakeList(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.OrderEntity> list, int roleType) {
            return base.Channel.GetOrderTakeList(loginID, order, pageindex, pagesize, ref page, ref list, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase GetOrderBackList(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.OrderEntity> list, int roleType) {
            return base.Channel.GetOrderBackList(loginID, order, pageindex, pagesize, ref page, ref list, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase UpdateBuyBackOrder(string loginID, string OrderCode, string agentID, int roleType) {
            return base.Channel.UpdateBuyBackOrder(loginID, OrderCode, agentID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase GetOrderJsjList(string loginID, Gss.BzjService.BZJServiceReference.OrderEntity order, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.OrderEntity> list, int roleType) {
            return base.Channel.GetOrderJsjList(loginID, order, pageindex, pagesize, ref page, ref list, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.ResultDesc CreateStockDeliverAdmin(string operationID, Gss.BzjService.BZJServiceReference.OrderEntity orderEnity, string loginID, int roleType) {
            return base.Channel.CreateStockDeliverAdmin(operationID, orderEnity, loginID, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase GetDeliverList(string loginID, string userID, int deliverType, string startTime, string endTime, int goods, int pageindex, int pagesize, ref int page, int roleType) {
            return base.Channel.GetDeliverList(loginID, userID, deliverType, startTime, endTime, goods, pageindex, pagesize, ref page, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.OrderEntity GetOrderNOInfo(string loginID, string orderCode, int roleType) {
            return base.Channel.GetOrderNOInfo(loginID, orderCode, roleType);
        }
        
        public Gss.BzjService.BZJServiceReference.EntityBase GetDeliverOrderList(string loginID, Gss.BzjService.BZJServiceReference.DeliverEntity entity, string name, int pageindex, int pagesize, ref int page, ref System.Collections.Generic.List<Gss.BzjService.BZJServiceReference.DeliverEntity> list, int roleType) {
            return base.Channel.GetDeliverOrderList(loginID, entity, name, pageindex, pagesize, ref page, ref list, roleType);
        }
    }
}
